# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.18.2-alpine AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN apk add --no-cache libc6-compat
RUN go build -o /duogo

##
## Deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /duogo /duogo

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/duogo"]
